server:
  port: 8080

spring:
  datasource:
    url: spring.datasource.url = jdbc:mysql://rm-2ze1jw9564ap5li9t3o.mysql.rds.aliyuncs.com:3306/delicioustest?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug